### ISSUE TITLE
use charset utf8

### ISSUE THREAD

**Issue by amuvsky** [amuvsky/web101#4]

**Comment by amuvsky** [comment]
@hrs113355 HIHI

**Comment by hrs113355** [comment]
I'll review later

amuvsky notifications@github.com 於 2015年9月19日 星期六寫道：

**Comment by amuvsky** [comment]
807e0adb99b0576703c1f82eeec8592bfb7db4ec

**Comment by hrs113355** [comment]
LGTM

![LGTM](http://lgtm.in/p/GFEAxSgwn)
